# Generated by Django 2.2.16 on 2022-05-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220510_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image2',
            new_name='image',
        ),
    ]
